### PR TITLE
fix(input[number]): validate min/max against viewValue

### LINKED ISSUE #12761: min/max input validation is against $modelValue, not $viewValue
Hi,

I am using ngModelController.$parsers/$formatters pipeline to do the number conversion and default min/max validators. My problem is that validation is done against $modelValue. So in my case when i enter value that is still valid in view validators reports it is invalid in model.

I want to propose to do default (min/max/etc.) validation on $viewValue. This way input limitations applied by browser would match validators rules.

I've made plunker to ilustrate: http://plnkr.co/edit/1IOnf9HYjgHhvpD0QsI3?p=preview

Cheers,
Edvinas

### PR DESCRIPTION
**Pull request by Narretz**
This brings the validation in line with HTML5 validation and all other
validators.

Fixes #12761

BREAKING CHANGE

....

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug fix / normalization

**What is the current behavior? (You can also link to an open issue here)**
See #12761

**What is the new behavior (if this is a feature change)?**
validation of min / max against viewValue

**Does this PR introduce a breaking change?**
Yes

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our [guidelines](../DEVELOPERS.md#commits)
- [ ] Fix/Feature: [Docs](../DEVELOPERS.md#documentation) have been added/updated
- [ ] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

I believe the BC is moderate enough to be included in 1.7

To switch the validation to the modelValue, it's as easy as adding this into a directive:

```
var minValidator = ngModelCtrl.$validators.max;

        ngModelCtrl.$validators.max = function(modelValue, viewValue) {
          return minValidator(modelValue, modelValue);
        };
```

I could even publish this is as a configurable third party directive that allows you to do this for any validator.

### CODE REVIEW

File: test/ng/directive/inputSpec.js [hunk 1]
```diff
@@ -2558,6 +2588,22 @@ describe('input', function() {
...
+
+      it('should validate against the viewValue', function() {
+        var inputElm = helper.compileInput('<input type="number"' +
+          'num-parse ng-model="value" name="alias" max="10" />');
+        var ngModelCtrl = inputElm.controller('ngModel');
+        ngModelCtrl.$parsers.push(function(value) {
+          return value + 5;
+        });
+
+        helper.changeInputValueTo('9');
```
Comment (gkalpak) [inline test/ng/directive/inputSpec.js]: Why not `10` (for symmetry with `min`)? 😢

**Review by gkalpak — APPROVED** [review]
LGTM (except for the missing "breaking change" notice on the commit message).

File: test/ng/directive/inputSpec.js [hunk 2]
```diff
@@ -2465,6 +2465,21 @@ describe('input', function() {
         expect($rootScope.form.alias.$error.min).toBeFalsy();
       });
 
+
+      it('should validate against the viewValue', function() {
+        var inputElm = helper.compileInput('<input type="number" num-parse ng-model="value" name="alias" min="10" />');
```
Comment (petebacondarwin) [inline test/ng/directive/inputSpec.js]: `num-parse` doesn't appear to be used anywhere

File: test/ng/directive/inputSpec.js [hunk 3]
```diff
@@ -2465,6 +2465,21 @@ describe('input', function() {
...
+        var ngModelCtrl = inputElm.controller('ngModel');
+        ngModelCtrl.$parsers.push(function(value) {
+          return value - 5;
+        });
+
+        helper.changeInputValueTo('10');
+        expect(inputElm).toBeValid();
+        expect($rootScope.value).toBe(5);
+        expect($rootScope.form.alias.$error.min).toBeFalsy();
```
Comment (petebacondarwin) [inline test/ng/directive/inputSpec.js]: Should we also have tests that check that we *do* get an error if the `viewValue` is bad but the `modelValue` is good?

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
LGTM
 - we should add tests for bad viewValue -> good modelValue
 - we need a BC notice that includes the example directive for reverting the behaviour.

**Comment by Narretz** [comment]
Updated with your suggestions!

**Review by petebacondarwin — APPROVED** [review]
Did you mean to capitalize "IF" in the commit message?
