### PR TITLE
fix(input): allow overriding timezone for date input types

### LINKED ISSUE #13382: input[type=datetime-local] does not support changing the timezone dynamically
The timezone can be set on `type="datetime-local"` inputs (e.g. `ng-model-options="{timezone: '+0400'}"`), but once the datetime picker has been created, changes to the timezone are not reflected in the edited value.

This plunk demonstrates the issue: http://plnkr.co/edit/R1cFGi23y0Eq2Fe7iN5h?p=preview - when you click the button then the timezone is put forward an hour, but this is not reflected in the time shown.

This happens in at least Chrome and Firefox on OS X, via angular `1.4.7`.

### LINKED ISSUE #16181: $overrideModelOptions does not apply timezone
I'm thinking is bug 

**Current behavior:**
Changing timezone programmatically (use $overrideModelOptions) dont work 

**Expected / new behavior:**
If we set new timezone, it apply to model

**Minimal reproduction of the problem with instructions:**
```
function ChangeModelOptionsDirective () {
  return {
    restrict: 'A',
    require: 'ngModel',
    link: function ($scope, element, attrs, ngModel) {
      ngModel.$overrideModelOptions({
	timezone: '+0400', // dont work
	debounce: {
	  'default': 5000 // it work
        }
     })	     
    }
  };
}
```
Plunker: [http://plnkr.co/edit/7zHR1EKigTMaFjDU1yDc?p=preview](http://plnkr.co/edit/7zHR1EKigTMaFjDU1yDc?p=preview)

**Angular version** - 1.6.5

### PR DESCRIPTION
**Pull request by Narretz**
Fixes #13382
Closes #16181

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
fix

**What is the current behavior? (You can also link to an open issue here)**
See https://github.com/angular/angular.js/issues/16181

**What is the new behavior (if this is a feature change)?**
overrideModelOptions can be used to change the timezone.

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](../DEVELOPERS.md#commits)
- [x] Fix/Feature: [Docs](../DEVELOPERS.md#documentation) have been added/updated
- [x] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

### CODE REVIEW

**Review by petebacondarwin — APPROVED** [review]
nice work @Narretz

File: test/ng/directive/inputSpec.js [hunk 1]
```diff
@@ -662,6 +662,21 @@ describe('input', function() {
...
+    it('should be possible to override the timezone', function() {
+      var inputElm = helper.compileInput('<input type="month" ng-model="value" ng-model-options="{timezone: \'UTC\'}" />');
+
+      helper.changeInputValueTo('2013-07');
+      expect(+$rootScope.value).toBe(Date.UTC(2013, 6, 1));
+
+      inputElm.controller('ngModel').$overrideModelOptions({timezone: '-0500'});
+
+      $rootScope.$apply(function() {
+        $rootScope.value = new Date(Date.UTC(2014, 6, 1));
```
Comment (gkalpak) [inline test/ng/directive/inputSpec.js]: Why the year change (here and below)? I would stick to the minimum necessary changes to avoid confusion.

**Review by gkalpak — COMMENTED** [review]
I wonder if we should document that changing the value timezone will have no effect until the next parse/format.

File: src/ng/directive/input.js [hunk 2]
```diff
@@ -1431,17 +1431,20 @@ function createDateInputType(type, regexp, parseDate, format) {
...
     badInputChecker(scope, element, attr, ctrl);
     baseInputType(scope, element, attr, ctrl, $sniffer, $browser);
-    var timezone = ctrl && ctrl.$options.getOption('timezone');
     var previousDate;
 
     ctrl.$$parserName = type;
     ctrl.$parsers.push(function(value) {
-      if (ctrl.$isEmpty(value)) return null;
+      if (ctrl.$isEmpty(value)) {
+        previousDate = null;
```
[the remark this answers is not in the document]
Comment (Narretz) [reply src/ng/directive/input.js]: If it's not valid, then why are there no test failures? :D
The formatter is doing the same thing afaict - it sets previousDate = null if the model is not a valid date (empty is not a valid date, too).
The specific test at https://github.com/angular/angular.js/pull/16336/files/d172e8ecb650ad3220e00e46b08325ad3672e9f1#diff-ce6d0f141f60d25eede7abf044d04b93R1968 shows that when clearing out the input, previousDate is still set and this leads the next input to use an incorrect value for the hour part.

We'd need a test case to show that this is a regression.

**Comment by Narretz** [comment]
Regarding the docs - any property changes in ngModelOptions only have an effect after the next update. We could add this info in overrideModelOptions generally.

File: src/ng/directive/input.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (gkalpak) [reply src/ng/directive/input.js]: > If it's not valid, then why are there no test failures? :D

Valid point...nooot 😛 

> The formatter is doing the same thing afaict - it sets `previousDate = null` if the model is not a valid date (empty is not a valid date, too).

That is the point. The formatter processes the model value and `previousDate` keeps track of the last valid (date) model value.

> The specific test at https://github.com/angular/angular.js/pull/16336/files/d172e8ecb650ad3220e00e46b08325ad3672e9f1#diff-ce6d0f141f60d25eede7abf044d04b93R1968 shows that when clearing out the input, previousDate is still set and this leads the next input to use an incorrect value for the hour part.

"use an incorrect value for the hour part" is subjective. I'd say currently it uses "the correct value for the hour part".
The idea is to be able to set the hour for a date field. AFAICT, the only way to achieve this today is by setting the model to a date with the desired date. Then, as the user edits the field (including emptying and refilling it) the hour/minute/second part is preserved. I think this is a desired property (I am pretty sure I've used it in my apps :smiley:).
In any case, I believe this change is breaking not related to this PR. It should go into a separate PR (where it can be debated further :grin:).

[the remark this answers is not in the document]
Comment (Narretz) [reply src/ng/directive/input.js]: > The idea is to be able to set the hour for a date field.

Ah, that's right. Did you get this from the code or did you search for the commit? Here's the commit: https://github.com/angular/angular.js/commit/1a1ef62903c8fdf4ceb81277d966a8eff67f0a96

As you can see, there are not tests for type=date ... :<

This is at least confusing, because as you can see in the test, the date is re-using the hour part that was set for -0500, even though the timezone is set to UTC again. But maybe this is a contrived example.

[the remark this answers is not in the document]
Comment (gkalpak) [reply src/ng/directive/input.js]: I didn't search for the commit (I didn't expect there to be a commit specific for that - I assumed it was part of the initial implementation) :smiley:

So, I am not sure what the correct behavior is here (wrt to changing the timezone) 😕
Maybe keep track of the previous timezone and re-adjust? Or accept the fact that changing the timezone may change the time part?
Timezones are tricky :grin:

**Comment by Narretz** [comment]
I've removed the date reset and added a different fix that should account for changing timezones. I'm not 100% happy with the implementation, but I also don't want to spend too much time on this.

**Comment by Narretz** [comment]
@gkalpak could you give this another look?

File: test/ng/directive/inputSpec.js [hunk 3]
```diff
@@ -931,6 +946,22 @@ describe('input', function() {
     });
 
 
+    it('should be possible to override the timezone', function() {
+      var inputElm = helper.compileInput('<input type="week" ng-model="value" ng-model-options="{timezone: \'UTC\'}" />');
+
+      helper.changeInputValueTo('2013-W03');
+      expect(+$rootScope.value).toBe(Date.UTC(2013, 0, 17));
+
+      inputElm.controller('ngModel').$overrideModelOptions({timezone: '+5000'});
```
Comment (gkalpak) [inline test/ng/directive/inputSpec.js]: Is this really supposed to be `+5000`?

File: test/ng/directive/inputSpec.js [hunk 4]
```diff
@@ -931,6 +946,22 @@ describe('input', function() {
...
+
+      $rootScope.$apply(function() {
+        // the 17. with an offset of +5000 moves the date into next week
```
Comment (gkalpak) [inline test/ng/directive/inputSpec.js]: Can you expand a bit on this comment? It mentions `17.` (which is in German format 😛), but the code uses `18`. Also, how does it move to the next week?

File: test/ng/directive/inputSpec.js [hunk 5]
```diff
@@ -1482,6 +1532,25 @@ describe('input', function() {
...
+
+      inputElm.controller('ngModel').$overrideModelOptions({timezone: '-0500'});
+      $rootScope.$apply(function() {
+        $rootScope.value = new Date(Date.UTC(1971, 0, 1, 23, 2, 0));
+      });
+      expect(inputElm.val()).toBe('18:02:00.000');
+
+      inputElm.controller('ngModel').$overrideModelOptions({timezone: 'UTC'});
+      helper.changeInputValueTo('23:02:00');
+      // The year is still set from the previous date
```
Comment (gkalpak) [inline test/ng/directive/inputSpec.js]: 👍

File: test/ng/directive/inputSpec.js [hunk 6]
```diff
@@ -1879,6 +1966,30 @@ describe('input', function() {
       dealoc(formElm);
     });
 
+    it('should not reuse the hour part of a previous date object after changing the timezone', function() {
```
Comment (gkalpak) [inline test/ng/directive/inputSpec.js]: Not sure how this test checks that the hour part of the previous date object isn't used.

File: src/ng/directive/input.js [hunk 7]
```diff
@@ -1431,17 +1431,27 @@ function createDateInputType(type, regexp, parseDate, format) {
...
       if (ctrl.$isEmpty(value)) return null;
+
       if (regexp.test(value)) {
+        var timezone = ctrl.$options.getOption('timezone');
+
         // Note: We cannot read ctrl.$modelValue, as there might be a different
         // parser/formatter in the processing chain so that the model
         // contains some different data format!
+        if (timezone && previousTimezone && previousTimezone !== timezone) {
+          // If the timezone has changed, adjust the previousDate to the default timzeone
```
Comment (gkalpak) [inline src/ng/directive/input.js]: _timzeone_ --> _timezone_

File: src/ng/directive/input.js [hunk 8]
```diff
@@ -1431,17 +1431,27 @@ function createDateInputType(type, regexp, parseDate, format) {
...
     ctrl.$parsers.push(function(value) {
       if (ctrl.$isEmpty(value)) return null;
+
       if (regexp.test(value)) {
+        var timezone = ctrl.$options.getOption('timezone');
+
         // Note: We cannot read ctrl.$modelValue, as there might be a different
         // parser/formatter in the processing chain so that the model
         // contains some different data format!
+        if (timezone && previousTimezone && previousTimezone !== timezone) {
```
Comment (gkalpak) [inline src/ng/directive/input.js]: Why do we need `timezone` or `previousTimezone` to be truthy? Don't we always need to adjust as long as `previousTimezone !== timezone`?

Comment (Narretz) [reply src/ng/directive/input.js]: We do need previousTimezone to be defined, since we pass it to addDateMinutes. timezone must not be defined, though.

File: test/ng/directive/inputSpec.js (hunk 3 above)
Comment (Narretz) [reply test/ng/directive/inputSpec.js]: Revised the test and added more comments.

File: test/ng/directive/inputSpec.js (hunk 6 above)
Comment (Narretz) [reply test/ng/directive/inputSpec.js]: Also Revised this test and added more comments.

**Review by Narretz — COMMENTED** [review]
I've revised the tests in hope that they are clearer now, or at least it's easier to understand them. Let me know if I have failed :D

File: test/ng/directive/inputSpec.js [hunk 9]
```diff
@@ -949,15 +949,23 @@ describe('input', function() {
...
+      });
+
+      expect(inputElm.val()).toBe('2013-W03');
 
-      inputElm.controller('ngModel').$overrideModelOptions({timezone: '+5000'});
+      inputElm.controller('ngModel').$overrideModelOptions({timezone: '+2400'});
 
+      //To check that the timezone overwrite works, apply an offset of +24 hours.
+      //Since January 19 is a Saturday, +24 will turn the formatted Date into January 20 - Sunday -
+      //which is in calendar week 4 instead of 3.
```
Comment (gkalpak) [inline test/ng/directive/inputSpec.js]: Missing whitspace after `//` 😇

File: test/ng/directive/inputSpec.js [hunk 10]
```diff
@@ -1966,28 +1974,32 @@ describe('input', function() {
...
+      // See https://github.com/angular/angular.js/commit/1a1ef62903c8fdf4ceb81277d966a8eff67f0a96
       inputElm.controller('ngModel').$overrideModelOptions({timezone: '-0500'});
       $rootScope.$apply(function() {
         $rootScope.value = new Date(Date.UTC(2000, 0, 1, 0));
       });
       expect(inputElm.val()).toBe('1999-12-31');
-
-      // Emptying the input should clear the cached date object
-      helper.changeInputValueTo('');
+      // At this point, the cached Date has its hours set to to 20 (00:00 - 05:00 = 19:00)
```
Comment (gkalpak) [inline test/ng/directive/inputSpec.js]: I am confused 😕
Are you saying that 19 === 20?

Comment (Narretz) [reply test/ng/directive/inputSpec.js]: No, just a result of trying to understand timezones. If you log a date, you always get it with the local timezone offset which is +1 for me, which means 20. But 19 is correct.
