### PR TITLE
fix(sanitizeUri): sanitize URIs that contain IDEOGRAPHIC SPACE chars

### LINKED ISSUE #16288: Test failure on Chrome 62
`````
Chrome 62.0.3202 (Windows 10 0.0.0) HTML should prevent mXSS attacks FAILED

       Expected '<a href="&#12288;javascript:alert(1)">CLICKME</a>' to be '<a>CLICKME</a>'.

           at Object.<anonymous> (test/ngSanitize/sanitizeSpec.js:242:71)
```

### PR DESCRIPTION
**Pull request by petebacondarwin**
Chrome 62 was not sanitizing dangerous URLs containing
JavaScript, if they started with these "whitespace" characters.

Closes #16288

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

fix

**What is the current behavior? (You can also link to an open issue here)**

#16288

**What is the new behavior (if this is a feature change)?**

URIs are sanitized correctly on Chrome 62

**Does this PR introduce a breaking change?**

No

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Review by mgol — APPROVED** [review]
We should make sure tests like that run in all supported browsers, not just Chrome.

**Comment by petebacondarwin** [comment]
I have removed the `isChrome` condition

**Comment by mgol** [comment]
The commit message is too long & it makes the build fail.

**Comment by Narretz** [comment]
I'm not sure if the description in this fix is 100% correct.
I've tested current Firefox, Chrome 62, 61, and 45 (version when the mxss fix was added), and Edge - none of these browsers execute javascript when it is preceeded by the IDEOGRAPHIC SPACE character.
http://plnkr.co/edit/DsOav9IHEdS5enbCxKsG?p=preview

So either the test is wrong, or the description is wrong (the string in the test is not dangerous, because it is not executed).

I think it makes sense to explicitly trim the string before sanitizing it though. The description should be more precise though.

**Comment by petebacondarwin** [comment]
@Narretz - you have to apply the "evil" text via `innerHTML` for the vulnerability to become apparent. This is due to mutation that browsers do when updating the DOM via this property. Hence the "m" in mXSS. 

You can see it happening on Chrome 61 here: https://plnkr.co/edit/Y6EsbsuDgd18YTn1oARu?p=preview

Background: http://www.nds.rub.de/media/emma/veroeffentlichungen/2013/12/10/mXSS-CCS13.pdf

**Comment by Narretz** [comment]
@petebacondarwin Thanks for clarifying. The part about innerHTML and the link should be a code comment or part of the commit message.

**Comment by petebacondarwin** [comment]
@Narretz  :-( after I just got Travis to go green too

**Comment by petebacondarwin** [comment]
I updated the commit message

**Comment by Narretz** [comment]
LGTM

File: test/ngSanitize/sanitizeSpec.js [hunk 1]
```diff
@@ -237,11 +237,9 @@ describe('HTML', function() {
       .toEqual('');
   });
 
-  if (isChrome) {
-    it('should prevent mXSS attacks', function() {
-      expectHTML('<a href="&#x3000;javascript:alert(1)">CLICKME</a>').toBe('<a>CLICKME</a>');
-    });
-  }
+  it('should prevent mXSS attacks', function() {
```
Comment (gkalpak) [inline test/ngSanitize/sanitizeSpec.js]: TBH, I don't think this test does what it says it does, but that is not related to this PR (it was like that before).
(It is more like `it should not be too strict in preventing mXSS aattacks` :smiley:)
