### PR TITLE
fix(formatNumber): better corner case handling

### LINKED ISSUE #8674: number formatter outputs NaN.0 for large numbers with decimals
http://plnkr.co/edit/bB1m5UOpLJJUIlHOYKAO?p=preview

For very large numbers when converting to a string the browser might use the "#e#" format which breaks the use of appending `"e"+fractionSize` and produces NaN.

The MDN page that `formatNumber` references appears to handle this by doing a `.split('e')` before generating the "#e#" string: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round

### LINKED ISSUE #10246: Number filter with exponentially small numbers without fractionSize
Currently, if `fractionSize` is not passed, for small numbers like `1e-50` number filter produces string `1e-50`.

It happens because `fractionSize` is undefined here: https://github.com/angular/angular.js/blob/g3_v1_3/src/ng/filter/filters.js#L152

`undefined + 1` is `NaN` and `NaN` can't be bigger than number.

Fraction size is only computed if number has no exponent.

Is it by design?

### LINKED ISSUE #12707: formatNumber produces NaN for numbers near 999999999999999934463
At the moment, the `formatNumber` method does some [hand built rounding](https://github.com/angular/angular.js/blob/master/src/ng/filter/filters.js#L180) for decimal numbers, in order to not lose precision.

It uses the `e` (scientific) notation (e.g. 1000e2) to shift the number and remove unnecessary precision, before rounding it and then doing the inverse `100000e-2` to return the number to it's original state.

If the number is already in scientific notation then it is [diverted away beforehand](https://github.com/angular/angular.js/blob/master/src/ng/filter/filters.js#L169). However, if the number is not in scientific notation, but scaling it up with `'e' + fractionSize` will take it above the browser's limit (999999999999999934463) then the string ends up with two `e`s. 

For example, take 444444444400000000000 and lets say we want to round it to 2 points of precision.

```
+(444444444400000000000 + 'e' + 2)
// becomes scientific notation
4.444444444e+22

// then we round it
Math.round(4.444444444e+22)
4.444444444e+22

// then we scale it back
4.444444444e+22 + 'e' + -2
"4.444444444e+22e-2"

// this version has two exponents and can't be coerced with +
+("4.444444444e+22e-2")
NaN
```

I think this issue may have already been opened as #8674, but the conditions for reproducing are a lot less clear in that issue.

### PR DESCRIPTION
**Pull request by petebacondarwin**
The idea here is that we actually parse the input number ourselves and then do the rounding ourselves manually. This allows us more control and reliability on the output for corner case numbers.

Closes #8674
Closes #12709 
Closes #8705 
Closes #12707 
Closes #10246
Closes #10252

### CODE REVIEW

**Comment by Narretz** [comment]
I've found another issue that seems to fit the theme: https://github.com/angular/angular.js/issues/10246 Maybe the PR fixes it?

**Comment by petebacondarwin** [comment]
I included the test from #10252 and it passes so I claim that this PR also fixes #10246

**Comment by petebacondarwin** [comment]
This PR is adding approximately 0.3% (181 bytes) to the gzipped and minified code size for `angular.js`.

File: src/ng/filter/filters.js [hunk 1]
```diff
@@ -139,93 +141,186 @@ function numberFilter($locale) {
...
+    while (numStr.charAt(--zeros) == ZERO_CHAR);
+    integerLen = e - i;
+    digits = [];
+    // Convert string to array of digits without leading/trailing zeros.
+    for (j = 0; i <= zeros; i++, j++) {
+      digits[j] = +numStr.charAt(i);
+    }
+  }
+
+  // if the overflow the maximum allowed digits then use an exponent
```
Comment (Narretz) [inline src/ng/filter/filters.js]: Can this be reworded? I think there's a word missing or one too many

File: src/ng/filter/filters.js [hunk 2]
```diff
@@ -139,93 +141,186 @@ function numberFilter($locale) {
...
 
-  var numStr = number + '',
-      formatedText = '',
-      hasExponent = false,
-      parts = [];
+    // determine fractionSize if it is not specified; `+fractionSize` converts it to a number
+    fractionSize = (isUndefined(fractionSize)) ? Math.min(Math.max(minFrac, fractionLen), maxFrac) : +fractionSize;
 
-  if (isInfinity) formatedText = '\u221e';
+    // The indec of the digit to where rounding is to occur
```
Comment (Narretz) [inline src/ng/filter/filters.js]: index

File: src/ng/filter/filters.js [hunk 3]
```diff
@@ -139,93 +141,186 @@ function numberFilter($locale) {
...
 
-  var isNegative = number < 0;
-  number = Math.abs(number);
+  if (i == (zeros = numStr.length)) {
+    // Zero.
+    digits = [0];
+    integerLen = 1;
+  } else {
+    // Determine trailing zeros.
+    while (numStr.charAt(--zeros) == ZERO_CHAR);
```
Comment (Narretz) [inline src/ng/filter/filters.js]: I find this hard too read. What does it even do?

File: src/ng/filter/filters.js [hunk 4]
```diff
@@ -139,93 +141,186 @@ function numberFilter($locale) {
...
+ * @param  {string} numStr The number to parse
+ * @return {object} An object describing this number, containing the following keys:
+ *  - d : an array of digits containing leading zeros as necessary
+ *  - i : the number of the digits in `d` that are to the left of the decimal point
+ *  - e : the exponent for numbers that would need more than `MAX_DIGITS` digits in `d`
+ *
+ */
+function parse(numStr) {
+  var exponent = 0, digits, integerLen;
+  var e, i, j, zeros;
```
Comment (Narretz) [inline src/ng/filter/filters.js]: `e` seems to have a bit more importance than i and j. Can it get a better name?

**Comment by petebacondarwin** [comment]
@Narretz - I updated after your comments and rebased. One more LGTM and I'll merge it.

**Comment by Narretz** [comment]
LGTM!
