### PR TITLE
fix(ngModelController): allow $overrideModelOptions to set updateOn

### LINKED ISSUE #16351: Better docs for ngModelOptions updateOn default events etc
WIP demo: http://plnkr.co/edit/wBGjCl2hvtdLOjVVMnVO?p=preview

### PR DESCRIPTION
**Pull request by Narretz**
Also adds more docs about "default" events and how to override
ModelOptions.

Closes #16351

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our [guidelines](../DEVELOPERS.md#commits)
- [ ] Fix/Feature: [Docs](../DEVELOPERS.md#documentation) have been added/updated
- [ ] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

### CODE REVIEW

**Comment by petebacondarwin** [comment]
I think, due to inheritance, that implementing this is more complicated than it seems. If a child ngModel is inheriting the current ngModelOptions, then changing the `updateOn` field on the parent would need to tell all descendant `ngModel`s to reapply their event handlers.

**Comment by Narretz** [comment]
I've added a note that overrideModelOptions does not propagate the changes. This is a  general problem - even the simple options like debounce, allowInvalid are not updated.
I personally think that this is an acceptable limitation, as overriding options should be a rather rare and specific operation.

File: src/ng/directive/ngModelOptions.js [hunk 1]
```diff
@@ -260,6 +264,106 @@ defaultModelOptions = new ModelOptions({
...
+            <td>{{key}}</td>
+            <td><input type="number" ng-model="$ctrl.events[key]" /></td>
+          </tr>
+        </table>
+
+        <br>
+        <input type="submit" value="Update options">
+      </form>
+ *   </file>
+ * </example>
```
Comment (gkalpak) [inline src/ng/directive/ngModelOptions.js]: This is one advanced example indeed. I am not even sure what it does 😛

File: src/ng/directive/ngModel.js [hunk 2]
```diff
@@ -877,11 +880,22 @@ NgModelController.prototype = {
    * See {@link ngModelOptions} for information about what options can be specified
    * and how model option inheritance works.
    *
+   * <div class="alert alert-warning">
+   * **Note:** overriding the model options with this function only affects the
+   * current `ngModelController` and does not propagate the new options to
+   * `ngModelOptions` directives that have initially inherited from it.
```
[the remark this answers is not in the document]
Comment (Narretz) [reply src/ng/directive/ngModel.js]: I wonder if the whole notice is irrelevant, as you can only $overrideModelOptions on ngModel, and nested ngModels are definitely "here be dragons" territory. Or should we mention that this doesn't change the options on ngModelOptions that this instance has inherited from?

File: src/ng/directive/ngModelOptions.js (hunk 1 above)
Comment (Narretz) [reply src/ng/directive/ngModelOptions.js]: Have you read the description? 😛

File: src/ng/directive/ngModel.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (gkalpak) [reply src/ng/directive/ngModel.js]: Actually, I think you are right. The inheritance is between `ngModelOptions` (which can be nested). `ngModel` just takes the options of its nearest `ngModuleOptions` and it can overwrite them. Where the corresponding `ngModelOptions` got its values (inherited or not) is not affected (nor is there any reason to assume it would).

File: src/ng/directive/ngModelOptions.js [hunk 3]
```diff
@@ -260,6 +264,106 @@ defaultModelOptions = new ModelOptions({
...
+              updateOn: 'default blur click',
+              debounce: {
+                default: 2000,
+                blur: 0,
+                '*': 1000
+              }
+            };
+
+            this.updateEvents = function() {
+              var eventL = this.options.updateOn.split(' ');
```
Comment (petebacondarwin) [inline src/ng/directive/ngModelOptions.js]: eventL?

**Review by petebacondarwin — APPROVED** [review]
LGTM - despite @gkalpak's sad face.
The extra explanatory docs are great.
