### PR TITLE
fix(ngRequired): set error correctly when inside ngRepeat and false b…

### LINKED ISSUE #16814: ng-required stopped working on 1.7.6 gravity-manipulation (2019-01-17)
- [ X] bug report

ng-required stopped working,

I am using AngularJS Material tabs,
I have a condition inside each tab for "required" fields.
I have another condition for showing the tabs or not (ng-if).

plunker: [http://next.plnkr.co/edit/g6tieIDq9yaEpNre](url)

In this example, the submit button is not working, but the ng-required for the second input (the hidden one) is false!

if we change angular version back to 1.7.5, its working as excepted.

**AngularJS version:**  1.7.6

**Browser:** [all ]

Thanks.

### PR DESCRIPTION
**Pull request by Narretz**
…y default

Previously, in the required validator, we would read the required setting directly from attr.required,
where it is set by ngRequired.

However, when the control is inside ngRepeat, ngRequired sets it only after a another digest has
passed, which means the initial validation run of ngModel does not include the correct required
setting. (Before commit 0637a2124c4515311a317e0e39926521228fc0af this would not have been a problem,
as every observed value change triggered a validation).

We now use the initially parsed value from ngRequired in the validator.

Fixes #16814

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ ] Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated
- [ ] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

### CODE REVIEW

File: test/ng/directive/validatorsSpec.js [hunk 1]
```diff
@@ -730,5 +730,20 @@ describe('validators', function() {
...
     });
+
+    it('should validate once when inside ngRepeat, and set the "required" error when ngRequired is false by default', function() {
+      $rootScope.isRequired = false;
+      $rootScope.refs = {};
+
+      var elm = helper.compileInput(
+        '<div ng-repeat="input in [0]">' +
+        '<input type="text" ng-ref="refs.input" ng-ref-read="ngModel" ng-model="value" ng-required="isRequired" validation-spy="required" />'
+        + '</div>'
```
Comment (gkalpak) [inline test/ng/directive/validatorsSpec.js]: The `+` sign placement seems weird (i.e. inconsistent - which is the ultimate form of weird 😛).
Did the linter have you do it like this, or is it a personal preference?

**Review by gkalpak — APPROVED** [review]

File: test/ng/directive/validatorsSpec.js (hunk 1 above)
Comment (Narretz) [reply test/ng/directive/validatorsSpec.js]: Ha, this happened because I tested without ngRepeat, and switching between with / without is easier if the concat plusses are at the start of the line

**Review by petebacondarwin — APPROVED** [review]
