### PR TITLE
fix($compile): throw error in $onChanges immediately

### LINKED ISSUE #15578: Errors throw from $onChanges result in an array passed to $exceptionHandler
**Do you want to request a *feature* or report a *bug*?**
bug?

**What is the current behavior?**
an error thrown in an `$onChanges` method results in [an array being thrown](https://github.com/angular/angular.js/blob/b77defde81fc265c13fa504dc78b41a43997abf4/src/ng/compile.js#L1528) which will result in `$exceptionHandler(arrayOfErrors)` 

**What is the expected behavior?**
`Error` objects are passed to `$exceptionHandler`

**What is the motivation / use case for changing the behavior?**
make `$exceptionHandler` more predictable / consistent / follow documentation

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
1.5+

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
Maybe each error in the array is passed to `$exceptionHandler` separately?
Maybe the array of errors is wrapped in an `Error` before being thrown?
Or document that `$exceptionHandler` might be passed an array?

### PR DESCRIPTION
**Pull request by Narretz**
This brings it in line with how we throw errors in a digest cycle.

Closes https://github.com/angular/angular.js/issues/15578

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ ] Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated
- [ ] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

### CODE REVIEW

File: src/ng/compile.js [hunk 1]
```diff
@@ -1562,14 +1562,11 @@ function $CompileProvider($provide, $$sanitizeUriProvider) {
             try {
               onChangesQueue[i]();
             } catch (e) {
-              errors.push(e);
```
Comment (gkalpak) [inline src/ng/compile.js]: You can get rid of the `errors` variable altogether.

**Review by gkalpak — APPROVED** [review]
