### PR TITLE
fix($compile): support transcluding multi-element directives

### LINKED ISSUE #15554: fix($compile): support transcluding multi-element directives
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**
Transcluding multi-element directives (e.g. `ng-repeat-start`/`ng-repeat-end`) is not supported on elements with multi-slot transclusion and a `$compile:uterdir` error is thrown.
Originally reported by @jamie-pate in https://github.com/angular/angular.js/issues/14653#issuecomment-269564856.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
[Reproduction][1].

**What is the expected behavior?**
Multi-element directives should be transcluded correctly on elements with multi-slot transclusion and without throwing.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Affects all Angular versions since a least 1.5.0 (including 1.6.x/master).

[1]: https://plnkr.co/edit/bMcETDXdd0EIpNiZG3wq?p=preview

### PR DESCRIPTION
**Pull request by gkalpak**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug fix.

**What is the current behavior? (You can also link to an open issue here)**
Transcluding multi-element directives (e.g. `foo-start`/`foo-end`) is not supported on elements with multi-slot transclusion (a `uterdir` error is thrown).

**What is the new behavior (if this is a feature change)?**
Transcluded nodes are put into a DocumentFragment, where they can be traversed via `.nextSibling`. This way, transcluding multi-element directives on elements with multi-slot transclusion works correctly.

**Does this PR introduce a breaking change?**
No.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] ~~Docs have been added / updated (for bug fixes / features)~~

**Other information**:
Fixes #15554.

### CODE REVIEW

File: src/ng/compile.js [hunk 1]
```diff
@@ -2480,7 +2480,7 @@ function $CompileProvider($provide, $$sanitizeUriProvider) {
 
               // We have transclusion slots,
               // collect them up, compile them and store their transclusion functions
-              $template = [];
+              $template = window.document.createDocumentFragment();
```
Comment (jbedard) [inline src/ng/compile.js]: Should this use $window or $document?

Comment (gkalpak) [inline src/ng/compile.js]: Other places inside this file use `window` directly (e.g. [here][1], [here][2] and [here][3]). Normally, I would prefer `$window` (or `$document`). But it doesn't bother me too much here because:

1. This file is dealing with pretty "low-level" stuff.
2. Switching to `$window` would be a breaking change (since every `$window` or `$document` mock should then provide the necessary APIs).

[1]: https://github.com/gkalpak/angular.js/blob/5a2db25b5d5d331f414894f3e13c096c8ec85779/src/ng/compile.js#L1495
[2]: https://github.com/gkalpak/angular.js/blob/5a2db25b5d5d331f414894f3e13c096c8ec85779/src/ng/compile.js#L1840
[3]: https://github.com/gkalpak/angular.js/blob/5a2db25b5d5d331f414894f3e13c096c8ec85779/src/ng/compile.js#L3389

**Comment by jbedard** [comment]
@gkalpak what's the status of this? Seems like a reasonable fix...

**Comment by gkalpak** [comment]
Waiting for approval :grin:

**Comment by Narretz** [comment]
LGTM with one question - does this affect  performance? Creating a document fragment is more expensive than creating an array. But I assume it's okay since it only happens for slot transclusion.

**Comment by gkalpak** [comment]
Yes, it olny affects directives with transclusion and yes it should be a little slower (not much though according to my [totally inadequate jsperf][1]) and I don't expect it to have any noticeable impact.

[1]: https://jsperf.com/angularjs-array-vs-documentfragment/1

**Comment by Narretz** [comment]
We'll find out :D
