### PR TITLE
fix(ngMockE2E): ensure that mocked $httpBackend uses correct $browser

### LINKED ISSUE #15593: waitForAngular does not wait for $httpBackend pass through requests
This change https://github.com/angular/angular.js/pull/13124 related to this issue https://github.com/angular/angular.js/issues/1434 caused this protractor issue https://github.com/angular/protractor/issues/3948.

Node v6.9.2
Protractor 4.0.14
Angular 1.5.8
Chrome 55.0.2883.87
Windows 7

### PR DESCRIPTION
**Pull request by petebacondarwin**
The fix from #13124 enabled ngMock and ngMockE2E to work together but
did it in a way that meant that the "real" `$httpBackend` service that
was used in pass-through depended upon a different `$browser` service
to the rest of the app.

This broke Protractor since it watches the `$browser` for outstanding
requests and the pass through requests were being tracked by the wrong
`$browser` instance.

Closes #15593

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
LGTM

File: test/ngMock/angular-mocksSpec.js [hunk 1]
```diff
@@ -2432,13 +2432,15 @@ describe('ngMock', function() {
...
-    var hb, realHttpBackend, callback;
+    var hb, realHttpBackend, realHttpBackendBrowser, callback;
 
     beforeEach(function() {
       callback = jasmine.createSpy('callback');
       angular.module('ng').config(function($provide) {
         realHttpBackend = jasmine.createSpy('real $httpBackend');
-        $provide.value('$httpBackend', realHttpBackend);
+        $provide.factory('$httpBackend', ['$browser', function($browser) {
+          return realHttpBackend.and.callFake(function() { realHttpBackendBrowser = $browser; });
```
Comment (petebacondarwin) [inline test/ngMock/angular-mocksSpec.js]: This way we would be able to be sure that the factory had been called but not that the correct httpBackend service had been called, no?

Comment (gkalpak) [inline test/ngMock/angular-mocksSpec.js]: Aren't you explicitly checking about the correct service anyway?
<sub>(I am not saying you should change it, just wondering.)</sub>

Comment (petebacondarwin) [inline test/ngMock/angular-mocksSpec.js]: Yes, we check that the spy has been called so I guess you are right.

Comment (petebacondarwin) [inline test/ngMock/angular-mocksSpec.js]: But since I have a LGTM from you and Travis is green I am going to merge it as-is :-P
