### PR TITLE
fix(orderBy): ensure correct ordering with arrays of objects and no predicate

### LINKED ISSUE #11866: orderBy doesn't reverse order if no predicate specified.
According to the documentation: https://docs.angularjs.org/api/ng/filter/orderBy.
> If no property is provided, (e.g. '+') then the array element itself is used to compare where sorting.

This seems to be working fine in 1.3.5 but it seems to have been broken in 1.3.6+.

Probably caused by: https://github.com/angular/angular.js/commit/8bfeddb5d671017f4a21b8b46334ac816710b143

Plnkr with the issue: http://plnkr.co/edit/vaOJzuDdkJUookDVSuDK?p=preview

### PR DESCRIPTION
**Pull request by petebacondarwin**
This fix also considerably refactors how the `orderBy` filter works in internally.

The new algorithm precomputes the predicate values for the array being ordered. This makes the algorith easier to follow but also ensures that this computation is done a maximum of n times, whereas in the previous algorithm it could be greater. The downside is that we must temporarily store this intermediate array.

There could be performance implications, but they are as likely to be beneficial as detrimental. It could probably do with benchmarking.

Closes #11866

### CODE REVIEW

**Comment by petebacondarwin** [comment]
@Narretz and wawyed could you take a look?

**Comment by petebacondarwin** [comment]
I guess this should be backported to 1.3.x - but not to 1.2.x since it uses `Array.map` and `Array.reduce`, which are not available in IE8.

**Comment by petebacondarwin** [comment]
Here is a plunker with this build of AngularJS demonstrating the original bug is fixed: http://plnkr.co/edit/WxAW671zu7BePcN4wgBn?p=preview

File: test/ng/filter/orderBySpec.js [hunk 1]
```diff
@@ -11,15 +11,15 @@ describe('Filter: orderBy', function() {
     it('should return sorted array if predicate is not provided', function() {
       expect(orderBy([2, 1, 3])).toEqual([1, 2, 3]);
 
-      expect(orderBy([2, 1, 3], '')).toEqual([1, 2, 3]);
-      expect(orderBy([2, 1, 3], [])).toEqual([1, 2, 3]);
-      expect(orderBy([2, 1, 3], [''])).toEqual([1, 2, 3]);
+      // expect(orderBy([2, 1, 3], '')).toEqual([1, 2, 3]);
+      // expect(orderBy([2, 1, 3], [])).toEqual([1, 2, 3]);
+      // expect(orderBy([2, 1, 3], [''])).toEqual([1, 2, 3]);
```
Comment (Narretz) [inline test/ng/filter/orderBySpec.js]: Is this intentionally commented out?

**Comment by wawyed** [comment]
Seems to be working fine when setting reverse true, although it doesn't seem to be working when using the '-' notation instead of reverse true for array with objects.

Pulnker with the issue:

http://plnkr.co/edit/Z3cdF3wMJ7Uzubw2Gma9?p=preview

File: test/ng/filter/orderBySpec.js (hunk 1 above)
Comment (petebacondarwin) [inline test/ng/filter/orderBySpec.js]: Oops. No

**Comment by petebacondarwin** [comment]
Agh! I knew it wasn't going to be so easy.
Now here is the problem. If you are reversing with a predicate then you need a way of telling the algorithm that objects should be ordered by index, rather than identity - but only if they don't have a `toString` or `toValue` or are being mapped by specific predicate.

**Comment by petebacondarwin** [comment]
OK, so I fixed it...

Actually, the reason for the refactoring was that it made this scenario much easier to handle.

But I am not 100% happy that we have to guess at whether the object is a POJO or not, when we decide to use the index rather than the identity for its ordering value.

Also, we now treat `null` as lower order than an object - hence the change to two of the tests. I don't think this should really affect anyone but perhaps it should be marked as a potential breaking change?

**Comment by petebacondarwin** [comment]
Agh! So safari wasn't happy comparing nulls, so I have now fixed that too

**Comment by petebacondarwin** [comment]
http://plnkr.co/edit/BSkUBBUfg0c9TJ9tTK5F?p=preview

**Comment by wawyed** [comment]
For example in this plunkr is this behaviour desired for the third ng-repeat?:

http://plnkr.co/edit/gyw8B10H9tpGdu77g1e7?p=preview

According to documentation if reverse is true it should reverse the order of the array, no matter what type the contents are. It's not that clear what it should do with '-'.

File: src/ng/filter/orderBy.js [hunk 2]
```diff
@@ -176,88 +176,110 @@
 orderByFilter.$inject = ['$parse'];
 function orderByFilter($parse) {
   return function(array, sortPredicate, reverseOrder) {
+
     if (!(isArrayLike(array))) return array;
-    sortPredicate = isArray(sortPredicate) ? sortPredicate : [sortPredicate];
+
+    if (!isArray(sortPredicate)) { sortPredicate = [sortPredicate]; }
     if (sortPredicate.length === 0) { sortPredicate = ['+']; }
```
Comment (lgalfaso) [inline src/ng/filter/orderBy.js]: Should this be
```js
sortPredicate.push('+');
```

?

File: src/ng/filter/orderBy.js [hunk 3]
```diff
@@ -176,88 +176,110 @@
...
-    sortPredicate = sortPredicate.map(function(predicate) {
-      var descending = false, get = predicate || identity;
-      if (isString(predicate)) {
+
+    var predicates = processPredicates(sortPredicate);
+    var compareValues = Array.prototype.map.call(array, getComparisonObject);
```
Comment (lgalfaso) [inline src/ng/filter/orderBy.js]: This is usually called *schwartzian transform*, a comment would help people understand what is going on

Comment (lgalfaso) [inline src/ng/filter/orderBy.js]: and please add Close #4282

File: src/ng/filter/orderBy.js [hunk 4]
```diff
@@ -176,88 +176,110 @@
...
+
+    compareValues.sort(doComparison);
+    array = compareValues.map(function(item) { return item.value; });
+    if (reverseOrder) { array.reverse(); }
```
Comment (lgalfaso) [inline src/ng/filter/orderBy.js]: Can this be made part of the main comparison?

File: src/ng/filter/orderBy.js (hunk 2 above)
Comment (lgalfaso) [inline src/ng/filter/orderBy.js]: Mmm... thinking a little more about this, I think my proposal and the current code are wrong as we are modifying the original `sortPredicate` and we should not do that

File: src/ng/filter/orderBy.js [hunk 5]
```diff
@@ -176,88 +176,110 @@
...
+      return {
+        value: value,
+        predicateValues: predicates.map(function(predicate) {
+          return getPredicateValue(predicate.get(value), index);
+        })
+      };
+    }
+
+    function doComparison(v1, v2) {
+      return predicates.reduce(function(result, predicate, index) {
```
Comment (lgalfaso) [inline src/ng/filter/orderBy.js]: this may be a little too fancy just to avoid a for-loop

**Comment by lgalfaso** [comment]
> Also, we now treat null as lower order than an object - hence the change to two of the tests. I don't think this should really affect anyone but perhaps it should be marked as a potential breaking change?

Do you think it would make the code any harder to keep the original behavior? I do not mind this going one way or another, but do think this is a small breaking change

**Comment by hamfastgamgee** [comment]
I'm guessing that this "small breaking change" might be accidentally fixing (or at least changing behavior of) #11312?

File: src/ng/filter/orderBy.js (hunk 2 above)
Comment (petebacondarwin) [inline src/ng/filter/orderBy.js]: I agree. We should not modify the passed in predicate

File: src/ng/filter/orderBy.js (hunk 5 above)
Comment (petebacondarwin) [inline src/ng/filter/orderBy.js]: I am not sure what is fancy about this. It is reducing a collection of comparison predicates down to a final comparison result.

Comment (petebacondarwin) [inline src/ng/filter/orderBy.js]: The for loop would look like:

```js
function doComparison(v1, v2) {
  var result = 0;
  for(var index=0, length = predicates.length; index<length; ++index) {
    result = result || compare(v1.predicateValues[index], v2.predicateValues[index]) * predicates[index].descending;
  }
  return result;
}
```

Comment (caitp) [inline src/ng/filter/orderBy.js]: honestly, for people who aren't familiar with `reduce`, this isn't significantly more readable, and is guaranteed to be slower. That and, comparison doesn't really map very well with the "reduce" operation

Comment (petebacondarwin) [inline src/ng/filter/orderBy.js]: @caitp The `reduce` is guaranteed to be slower?

Comment (caitp) [inline src/ng/filter/orderBy.js]: yes --- the spec mandates `HasProperty` checks for each item which are slow almost everywhere, and can't be optimized away because the callback can manipulate the array

Comment (caitp) [inline src/ng/filter/orderBy.js]: Basically for something that runs each digest on a potentially large collection, I'd prefer if it wasn't a reduce operation, both for readability and perf

File: src/ng/filter/orderBy.js (hunk 2 above)
Comment (gkalpak) [inline src/ng/filter/orderBy.js]: How is the current implementation modifying the passed in predicate ?

File: src/ng/filter/orderBy.js (hunk 5 above)
Comment (petebacondarwin) [inline src/ng/filter/orderBy.js]: OK, I'll change this

**Comment by petebacondarwin** [comment]
I think we can probably move `null` in the sort order. I need to work out exactly where that is though.

File: src/ng/filter/orderBy.js (hunk 4 above)
Comment (petebacondarwin) [inline src/ng/filter/orderBy.js]: It could but if you look at the previous implementation it meant complicating the processing of the predicate functions, which makes it significantly more messy.
What is the cost of `Array.reverse()`? It would seem to me that it could be done rather quickly inside the JavaScript engine. Any thoughts @caitp ?

Comment (petebacondarwin) [inline src/ng/filter/orderBy.js]: Actually, it is simple to move this into the predicates.

File: src/ng/filter/orderBy.js (hunk 2 above)
Comment (petebacondarwin) [inline src/ng/filter/orderBy.js]: It's not. But I agree that we should start doing that either :-)

**Comment by petebacondarwin** [comment]
No breaking change no more: the algorithm sorts nulls in the same way as `array.sort()`.
Objects are now dealt with in the following manner:

* has a valid `toValue()` method: sort on the return value of this method
* has a valid custom `toString()` method (i.e. not `Object.prototype.toString()`): sort on the return value of this method
* otherwise sort on index of the object in the array

This means that dates are sorted as expected, but also that arrays are sorted by their `toString` representation, which is to convert each item to a string and then join them together, separated by commas. This gives the same result as calling `array.sort()` on such an array of arrays.

I have noted that the idiom used is a Schwartzian Transform and that it closes #4282.

File: src/ng/filter/orderBy.js [hunk 6]
```diff
@@ -176,88 +176,110 @@
...
+        value: value,
+        predicateValues: predicates.map(function(predicate) {
+          return getPredicateValue(predicate.get(value), index);
+        })
+      };
+    }
+
+    function doComparison(v1, v2) {
+      var result = 0;
+      for (var index=0, length = predicates.length; index < length; ++index) {
```
Comment (lgalfaso) [inline src/ng/filter/orderBy.js]: for (...; !result && index < length; ...) {

?

File: src/ng/filter/orderBy.js [hunk 7]
```diff
@@ -176,88 +176,110 @@
...
+  function objectValue(value, index) {
+    if (typeof value.valueOf === 'function') {
+      value = value.valueOf();
+      if (isPrimitive(value)) return value;
+    }
+    if (hasCustomToString(value)) {
+      value = value.toString();
+      if (isPrimitive(value)) return value;
     }
+    return index;
```
Comment (lgalfaso) [inline src/ng/filter/orderBy.js]: trying to think when we end up returning `index` and what does it mean

File: src/ng/filter/orderBy.js (hunk 6 above)
Comment (petebacondarwin) [inline src/ng/filter/orderBy.js]: I like

File: src/ng/filter/orderBy.js (hunk 7 above)
Comment (petebacondarwin) [inline src/ng/filter/orderBy.js]: I'll add a comment. Is that enough or are you saying that the code might be wrong?

File: src/ng/filter/orderBy.js (hunk 6 above)
Comment (petebacondarwin) [inline src/ng/filter/orderBy.js]: But it is a bit obscure. I would prefer to make it more explicit:

```js
    function doComparison(v1, v2) {
      var result = 0;
      for (var index=0, length = predicates.length; index < length; ++index) {
        result = compare(v1.predicateValues[index], v2.predicateValues[index]) * predicates[index].descending;
        if (result) break;
      }
      return result;
    }
```

**Comment by petebacondarwin** [comment]
@lgalfaso I updated the code.

File: src/ng/filter/orderBy.js (hunk 7 above)
Comment (lgalfaso) [inline src/ng/filter/orderBy.js]: > In src/ng/filter/orderBy.js
> <https://github.com/angular/angular.js/pull/12072#discussion_r32614045>:
>
> >      }
> > +    return index;
>
> I'll add a comment. Is that enough or are you saying that the code might
> be wrong?
>

Before, we had that if the property was an object (that does not meet a
criteria) then the value was the blank string. Now it returns the position
in the index of the object.

This is, if you sort [{foo: 2}, {foo: 3}, {foo: 4}, {foo: {}}] by "foo",
over and over, then sorting it once will be different than sorting it twice
(assuming sort is stable)

Comment (petebacondarwin) [inline src/ng/filter/orderBy.js]: Well.... it is true that the sort will change on the second pass but I think it is reasonable to say that sorting mixed types like that is a rather strange case, no?

Comment (petebacondarwin) [inline src/ng/filter/orderBy.js]: Actually, this is not a problem. First of all the `orderBy` filter does not mutate the original array. Second if the types of things are different then they are ordered by their type first rather than their value.

File: src/ng/filter/orderBy.js (hunk 6 above)
Comment (lgalfaso) [inline src/ng/filter/orderBy.js]: Works for me

File: src/ng/filter/orderBy.js (hunk 7 above)
Comment (lgalfaso) [inline src/ng/filter/orderBy.js]: I think this is very minor (famous last words), so there is no needs to keep this going on. Lets land this

**Comment by lgalfaso** [comment]
LGTM
