### PR TITLE
fix(select): keep original selection when using shift to add options …

### LINKED ISSUE #15675: not able to select multiple options on IE with ng-model
Reporting Bug: Not able select multiple options sequentially (shift+down/up arrow alone) when binded with ng-model on IE alone (tested versions IE edge, 10, 9)

Current behavior: Not allowing more than two options to be selected

JSFiddle sample code: http://jsfiddle.net/JB3Un/597/
https://plnkr.co/edit/?p=preview
This issue can be reproduced with the angular documentation sample as well for multi select.

Expected behavior: Should be able to select more than two options sequentially and should hold all the sequence for both shift+ up/down arrow

OS: windows 10
Browser: IE edge, 10, 9
AngularJS: 1.6.2

### PR DESCRIPTION
**Pull request by Narretz**
…in IE/Edge

In IE9-11 + Edge, the selected options were previously incorrect under the following
circumstances:
- at least two options are selected
- shift+click or shift+down/up is used to add to the selection (any number of options)

In these cases, only the last of the previously selected options and the newly selected
options would be selected.

The problems seems to be that the render engine gets confused when an option that
already has selected = true gets selected = true set again.

Note that this is not testable via unit test because it's not possible to simulate
click / keyboard events on option elements (the events are delegated to the select element
change event).

Fixes #15675

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bugfix

**What is the current behavior? (You can also link to an open issue here)**
See #15675

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- ~~[ ] Tests for the changes have been added (for bug fixes / features)~~
- ~~[ ] Docs have been added / updated (for bug fixes / features)~~

**Other information**:

### CODE REVIEW

File: src/ng/directive/select.js [hunk 1]
```diff
@@ -607,8 +607,17 @@ var selectDirective = function() {
...
-            option.selected = !!value && (includes(value, option.value) ||
-                                          includes(value, selectCtrl.selectValueMap[option.value]));
+            var shouldBeSelected = !!value && (includes(value, option.value) ||
+                                                includes(value, selectCtrl.selectValueMap[option.value]));
+            var currentlySelected = option.selected;
+
+            // IE and Edge will de-select selected options when you set the selected property again, e.g.
+            // when you add to the selection via shift+click/UP/DOWN
+            // Therefore, only set it if necessary
+            if ((shouldBeSelected && !currentlySelected) || (!shouldBeSelected && currentlySelected)) {
```
Comment (jbedard) [inline src/ng/directive/select.js]: `shouldBeSelected !== currentlySelected`?

Comment (Narretz) [inline src/ng/directive/select.js]: Oh, I had the feeling this could be simpler :D

File: src/ng/directive/select.js [hunk 2]
```diff
@@ -607,8 +607,17 @@ var selectDirective = function() {
         // Write value now needs to set the selected property of each matching option
         selectCtrl.writeValue = function writeMultipleValue(value) {
           forEach(element.find('option'), function(option) {
-            option.selected = !!value && (includes(value, option.value) ||
-                                          includes(value, selectCtrl.selectValueMap[option.value]));
+            var shouldBeSelected = !!value && (includes(value, option.value) ||
+                                                includes(value, selectCtrl.selectValueMap[option.value]));
```
Comment (gkalpak) [inline src/ng/directive/select.js]: Nit: Align with `includes` above.

File: src/ng/directive/select.js (hunk 1 above)
Comment (gkalpak) [inline src/ng/directive/select.js]: If you swithc to `!==` you need to make sure both values are booleans.
(I am not sure about `option.selected`. Theoretically it should always be boolean, but you never know especially with older browsers.)

**Review by gkalpak — APPROVED** [review]
Couldn't this be tested by directly calling `selectCtrl.writeValue`?

**Comment by Narretz** [comment]
I tried to test it directly with the selectCtrl API, but this doesn't replicate the bug. It must have something to do with the ui of the select box in IE / Edge.

**Comment by gkalpak** [comment]
Maybe we could just test that we don't re-set the `selected` property. (I just realized this seems equivalent to #15478, but using `<option>` instead of `ngOptions`).

Maybe something like [this][1] would work (although it borderline testing "implementation details").

[1]: https://github.com/angular/angular.js/pull/15478/files#diff-2cda0d7a6d8ec47da3560fbe59a634e3R2847

**Comment by Narretz** [comment]
Hm. I agree that this is an implementation detail. I'll let you decide if I should add this test or not.

File: src/ng/directive/select.js [hunk 3]
```diff
@@ -607,8 +607,24 @@ var selectDirective = function() {
...
+            // IE and Edge, adding options to the selection via shift+click/UP/DOWN,
+            // will de-select already selected options if "selected" on those options was set
+            // more than once (i.e. when the options were already selected)
+            // So we only modify the selected property if neccessary.
+            // Note: this behavior cannot be replicated via unit tests because it only shows in the
+            // actual user interface.
+            if ((shouldBeSelected && !currentlySelected)) {
+              setOptionAsSelected(jqLite(option));
+            } else if ((!shouldBeSelected && currentlySelected)) {
+              option.selected  = shouldBeSelected;
```
Comment (gkalpak) [inline src/ng/directive/select.js]: I wonder why we are using `option.selected` here, but `option.prop('selected', true)` in `setOptionAsSelected()`.
Probably doesn't matter, so we should use the same for consistency. In fact, I think it is better to make `setOptionSelected()` a helper that can both select and unselect an option and use that whenever needed.

Comment (gkalpak) [inline src/ng/directive/select.js]: (BTW, there is a double space before the `=` 😱

**Review by gkalpak — CHANGES_REQUESTED** [review]
"No test" is fine by me.

File: src/ng/directive/select.js [hunk 4]
```diff
@@ -4,9 +4,16 @@
 
 var noopNgModelController = { $setViewValue: noop, $render: noop };
 
-function setOptionAsSelected(optionEl) {
-  optionEl.prop('selected', true); // needed for IE
-  optionEl.attr('selected', true);
+function setOptionSelectedStatus(optionEl, value) {
+  optionEl.prop('selected', value); // needed for IE
+  if (value) {
+    optionEl.attr('selected', value);
```
Comment (gkalpak) [inline src/ng/directive/select.js]: FWIW: `.attr('selected', null)` also removes the attribute. So, this could be:

```js
optionEl.prop('selected', value);
optionEl.attr('selected', value || null);
```

**Review by gkalpak — APPROVED** [review]

File: src/ng/directive/select.js [hunk 5]
```diff
@@ -4,6 +4,16 @@
...
 var noopNgModelController = { $setViewValue: noop, $render: noop };
 
+function setOptionSelectedStatus(optionEl, value) {
+  optionEl.prop('selected', value); // needed for IE
+  /**
+   * When unselecting an option, setting the property to null / false should be enough
+   * However, screenreaders might react to the selected attribute instead, see
+   * https://github.com/angular/angular.js/issues/14419
+   */
+  optionEl.attr('selected', value || null);
```
Comment (gkalpak) [inline src/ng/directive/select.js]: I said it works, but do we have tests that the property is actually removed? 😛

Comment (Narretz) [inline src/ng/directive/select.js]: Oh, you little rascal! 
We have the toBeMarkedAsSelected() custom matcher which complains when the selected attr is in the wrong state. And jqlite also removes the attribute when you pass `false` and the element is boolean. So I'm going with that.
