### PR TITLE
fix(ngOptions): override select option registration

### LINKED ISSUE #11685: Hard coded <option> causes error "TypeError: Cannot read property 'getOptionFromViewValue' of undefined"
Hi, in documentation is stated that 'empty option' can be used when using ng-options. Here is direct quote

> Optionally a single hard-coded **option** element, with the value set to an empty string, can be nested into the **select** element. This element will then represent the null or "not selected" option

I used that in 1.3 very heavily  and it worked flawlessly, but in 1.4 i'm getting error
```
TypeError: Cannot read property 'getOptionFromViewValue' of undefined
```

Just to be clear, here is the template i'm using

```html
<select ng-options="option.id as option.name for option in selectable_options">
  <option value="">Choose an option</option>
</select>
```

Is this planed regression or a bug? If this is planed regression, is there a workaround for the thing i'm trying to accomplish?

### PR DESCRIPTION
**Pull request by petebacondarwin**
When ngOptions is present on a select, the option directive should not be able to
register options on the selectCtrl since this may cause errors during the
ngOptions lifecycle.

This can happen in the following cases:
- there is a blank option below the select element, an ngModel
  directive, an ngOptions directive and some other directive on the select
  element, which compiles the children of the select
  (i.e. the option elements) before ngOptions is has finished linking.
- there is a blank option below the select element, an ngModel
  directive, an ngOptions directive and another directive, which uses
  templateUrl and replace:true.

What happens is:
- the option directive is compiled and adds an element `$destroy` listener
  that will call `ngModel.$render` when the option element is removed.
- when `ngOptions` processes the option, it removes the element, and
  triggers the `$destroy` listener on the option.
- the registered `$destroy` listener calls `$render` on `ngModel`.
- $render calls `selectCtrl.writeValue()`, which accesses the `options`
  object in the `ngOptions` directive.
- Since `ngOptions` has not yet completed linking the `options` has not
  yet been defined and we get an error.

This fix moves the registration code for the `option` directive into the
`SelectController`, which can then be easily overridden by the `ngOptions`
directive as a `noop`.

Fixes #11685
Closes #12972
Closes #12968

### CODE REVIEW

File: src/ng/directive/select.js [hunk 1]
```diff
@@ -98,6 +109,39 @@ var SelectController =
   self.hasOption = function(value) {
     return !!optionsMap.get(value);
   };
+
+
+  self.register = function($scope, $optionElement, $optionAttrs, interpolateValueFn, interpolateTextFn) {
```
Comment (Narretz) [inline src/ng/directive/select.js]: can we call it `registerOption`?

Comment (Narretz) [inline src/ng/directive/select.js]: Also, we inject `$scope` into the selectController. It's possibly a bit confusing to have a parameter with the same name in this fn.

Comment (petebacondarwin) [inline src/ng/directive/select.js]: OK, so I'll change the function to :+1: 

```js

replaceOption($optionScope, $optionElement, $optionAttrs, interpolateValueFn, interpolateTextFn) { ... }
```

OK?

Comment (Narretz) [inline src/ng/directive/select.js]: Is replaceOption a typo? Otherwise sgtm

Comment (gkalpak) [inline src/ng/directive/select.js]: Why the `$`-prefix in the first 3 args ?

Comment (petebacondarwin) [inline src/ng/directive/select.js]: Yes, I meant `registerOption` :-)

So in the Angular code, elements that are wrapped in jqLite are prefixed with a dollar, and I always prefer to do the same with the attributes and scope, since they are "Angular" things, not from the user's application space. I guess that this is not that common so I don't mind dropping them if they would cause confusion.

**Comment by godza** [comment]
Great news. Thanks!

**Comment by petebacondarwin** [comment]
Backported to 1.4 too
