### PR TITLE
fix($compile): don't run unnecessary update to one-way bindings

### LINKED ISSUE #14546: Outer change is stronger than the inner one when they are both changed and using one-way binding
**Do you want to request a *feature* or report a *bug*?**
Bug (?)

**What is the current behavior?**
I'm not sure if bug or by design, but when using one-way (`<`), if both the outer and inner scope have been changed, the outer is stronger, **even if the inner's change happened after the outer one**.
http://jsbin.com/zunoraquju/1/edit?html,js,output

**What is the expected behavior?**
I would simply expect that the last change is stronger, that's what happens till now with two-way (`=`). You can change my attached example to `=` and it will work.

**What is the motivation / use case for changing the behavior?**
Actually a common case - if the passed value is `X` I want to change it to be `Y` (in constructor / `$onInit`) and display it, but preserve the one-way so the outer scope won't get the update.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
`1.5+`

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
[Relevant test](https://github.com/angular/angular.js/commit/4ac23c0ac59c269d65b7f78efec75d060121bd18#diff-348c2f3781ed66a24894c2046a52c628R4268) (I would expect it to be `misko`)

### PR DESCRIPTION
**Pull request by petebacondarwin**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Bug Fix

**What is the current behavior? (You can also link to an open issue here)**

The watch handler was triggering on its first invocation, even though
its change had already been dealt with when setting up the binding.

**What is the new behavior (if this is a feature change)?**

The handler does not trigger an update on its first invocation

**Does this PR introduce a breaking change?**

Nope - I don't think so. Although I had to modify a bunch of tests to ensure that a digest occurred between compilation and the first checks.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
  ~~\- [ ] Docs have been added / updated (for bug fixes / features)~~

**Other information**:

Closes #14546

### CODE REVIEW

File: test/ng/compileSpec.js [hunk 1]
```diff
@@ -3756,6 +3760,7 @@ describe('$compile', function() {
         module('my');
         inject(function($compile, $rootScope) {
           element = $compile('<c1 prop1="val"></c1>')($rootScope);
+          $rootScope.$apply();
```
Comment (gkalpak) [inline test/ng/compileSpec.js]: Why is this needed ?

File: test/ng/compileSpec.js [hunk 2]
```diff
@@ -4796,6 +4814,35 @@ describe('$compile', function() {
...
+          });
+        module('owComponentTest');
+        inject(function() {
+          $rootScope.name = 'outer';
+          compile('<ow-component input="name"></ow-component>');
+          $rootScope.$apply();
+
+          expect($rootScope.name).toEqual('outer');
+          expect(component.input).toEqual('$onInit');
+        })
```
Comment (gkalpak) [inline test/ng/compileSpec.js]: Missing semicolon.

File: test/ng/compileSpec.js [hunk 3]
```diff
@@ -4796,6 +4814,35 @@ describe('$compile', function() {
...
+            bindings: { input: '<' },
+            controller: function() {
+              component = this;
+              this.input = 'constructor';
+              this.$onInit = function() {
+                this.input = '$onInit';
+              };
+              this.$onChanges = function(changes) {
+                if (changes.input) {
+                  log.push(changes.input);
```
Comment (gkalpak) [inline test/ng/compileSpec.js]: You are pushing to `log`, but never checking what was actually pushed.

Comment (petebacondarwin) [inline test/ng/compileSpec.js]: Fixed.

File: test/ng/compileSpec.js (hunk 1 above)
Comment (petebacondarwin) [inline test/ng/compileSpec.js]: If we have no digest before changing the value of `val` then effectively the system thinks that `val` has not changed, so `$onChanges` is not called.

**Comment by gkalpak** [comment]
One testcase I believe should work, but doesn't, is when the parent value changes after initializing the bindings but before the first call to the one-way binding watcher callback.
Here are a couple of unit tests demonstrating the issue. They are essentially equivalent, the first being more straight-forward and the latter being more "real-world-ish".

```js
      it('should update isolate again after $onInit if outer has changed (before initial watchAction call)', function() {
        var log = [];
        var component;
        angular.module('owComponentTest', [])
          .component('owComponent', {
            bindings: { input: '<' },
            controller: function() {
              component = this;
              this.input = 'constructor';
              this.$onInit = function() {
                this.input = '$onInit';
              };
              this.$onChanges = function(changes) {
                if (changes.input) {
                  log.push(changes.input);
                }
              };
            }
          });
        module('owComponentTest');
        inject(function() {
          $rootScope.name = 'outer1';
          compile('<ow-component input="name"></ow-component>');

          expect(component.input).toEqual('$onInit');
          $rootScope.$apply('name = "outer2"');

          expect($rootScope.name).toEqual('outer2');
          expect(component.input).toEqual('outer2');
        });
      });

      it('should update isolate again after $onInit if outer has changed (before initial watchAction call)', function() {
        var log = [];
        var component;
        angular.module('owComponentTest', [])
          .directive('changeInput', function() {
            return function(scope, elem, attrs) {
              scope.name = 'outer2';
            };
          })
          .component('owComponent', {
            bindings: { input: '<' },
            controller: function() {
              component = this;
              this.input = 'constructor';
              this.$onInit = function() {
                this.input = '$onInit';
              };
              this.$onChanges = function(changes) {
                if (changes.input) {
                  log.push(changes.input);
                }
              };
            }
          });
        module('owComponentTest');
        inject(function() {
          $rootScope.name = 'outer1';
          compile('<ow-component input="name" change-input></ow-component>');

          expect(component.input).toEqual('$onInit');
          $rootScope.$digest();

          expect($rootScope.name).toEqual('outer2');
          expect(component.input).toEqual('outer2');
        });
      });
```

**Comment by gkalpak** [comment]
BTW, in order to support these usecases (and fix the original bug), we could change `if (oldValue === newValue) return` to:

```js
if (oldValue === newValue) {
  if (oldValue === initialValue) return;
  oldValue = destination[scopeName];
}
```

**Comment by gkalpak** [comment]
BTW, in order to support these usecases (and fix the original bug), we could change the code from:

```js
destination[scopeName] = parentGet(scope);
...

removeWatch = scope.$watch(parentGet, function parentValueWatchAction(newValue, oldValue) {
  if (oldValue === newValue) return;
  ...
```

to:

```js
var initialValue = destination[scopeName] = parentGet(scope);
...

removeWatch = scope.$watch(parentGet, function parentValueWatchAction(newValue, oldValue) {
  if (oldValue === newValue) {
    if (oldValue === initialValue) return;
    oldValue = initialValue;
  }
  ...
```

File: test/ng/compileSpec.js [hunk 4]
```diff
@@ -4796,6 +4800,96 @@ describe('$compile', function() {
...
+            $rootScope.name = 'outer';
+            compile('<ow-component input="name"></ow-component>');
+
+            expect($rootScope.name).toEqual('outer');
+            expect(component.input).toEqual('$onInit');
+            expect(log).toEqual([
+              'constructor',
+              ['$onChanges', jasmine.objectContaining({ currentValue: 'outer' })],
+              '$onInit'
+            ]);
```
Comment (gkalpak) [inline test/ng/compileSpec.js]: Wouldn't this test pass even without the fix ? (I haven't tested it, but I think so.)
I think it's a good idea to add a `$rootScope.$digest()` and another round of expectation to make sure that nothing is overwritten when the watch callback is executed.

File: test/ng/compileSpec.js [hunk 5]
```diff
@@ -4796,6 +4800,96 @@ describe('$compile', function() {
...
+          });
+        });
+
```
Comment (gkalpak) [inline test/ng/compileSpec.js]: <sub>Inconsistent number of newlines between tests :grin:</sub>

**Comment by gkalpak** [comment]
A couple of minor test-related comments.
Otherwise LGTM :+1:

File: test/ng/compileSpec.js (hunk 4 above)
Comment (petebacondarwin) [inline test/ng/compileSpec.js]: OK. It did fail before the fix. But then I might have changed it again since then.

File: test/ng/compileSpec.js (hunk 5 above)
Comment (petebacondarwin) [inline test/ng/compileSpec.js]: Shock horror! Isn't there a JSCS rule for that??

File: test/ng/compileSpec.js (hunk 4 above)
Comment (petebacondarwin) [inline test/ng/compileSpec.js]: It totally fails as it is without the fix. But I will add the extra digest and check

**Comment by khoomeister** [comment]
Hey, this just broke a whole bunch of our unit tests which I was hoping to get some clarification on.

So right now, we have something like this:

```typescript
export someComponent = {
  ...

  set config(config: Config) {
    if (!this.state) return
    this.state.config = config
  }
}

angular.component('someComponent', someComponent)
```

The reason for the `if (!this.state) return` line is because [prototype accessors are called before the constructor](https://github.com/angular/angular.js/issues/12865), and we need to do a number of things in the constructor (not least setting up `this.state`) before the config setter is called again.

We can't move the constructor code since we rely on injected dependencies to do some setup.  Perhaps there's a better pattern for what we want to do but not sure how our use case can be accomplished.  Do you have any ideas on what to do here?

**Comment by gkalpak** [comment]
TBH, I don't get what the problem is. Could you share some more code and/or tests.

**Comment by khoomeister** [comment]
Hey @gkalpak the issue we're encountering is basically very similar to #13590 - I guess we just need to work around it.

**Comment by khoomeister** [comment]
Just to give you some context, setters got called twice on startup (once before the component controller instantiates and once after).  We relied on the behavior that setters got called after instantiation since dependencies are available at that point.  Since this change returns early for matching values, our setter doesn't execute.

**Comment by khoomeister** [comment]
OK I see the angular way of doing this is to hook into `$onChanges` :smiley: - thx!

**Comment by gkalpak** [comment]
Glad you got it working with `$onChanges` :smiley:
I'm still not sure what your code does and how it is afected by this, but you might also want to look into `$onInit`.

**Comment by bcherny** [comment]
@gkalpak I think what @khoomeister is saying is that in 1.5.5, the order of calls was setter-constructor-setter. So on the first fire `this.state` was undefined and the setter returned early, then the constructor defined `this.state`, then the setter fired again (successfully this time, because `this.state` was now defined).

In 1.5.6, that 2nd call to the setter never happens, so the setter is never fully executed.

This is a *breaking change* for anyone that relies on something being defined on `this` in a setter!

**Comment by gkalpak** [comment]
@bcherny, it will be easier to investigate with an actual example, but this is expected bahavior as far as I understand. The fact that it worked differently in 1.5.5 (i.e. overwriting the inner value even though the outer vaue hadn't changed) was a bug. This commit is restoring the expacted/correct behavior and thus is not considered a breaking change (although it would break a usecase that relied on the buggy behavior).

The proper way to ensure something is run after the bindings have been initialized is using an appropriate hook (e.g. `$onInit` or `$onChanges` - depending on the usecase).

**Comment by bcherny** [comment]
@gkalpak Demo here - http://codepen.io/anon/pen/EyVyzB

**Comment by gkalpak** [comment]
@bcherny, fwiw it is expected behavior. The actual "problem" with your usecase is not how one-way binding watches are triggered, but the fact that we are pre-assigning the binding values on the controller instance before actually instantiating it.

Although this is supposed to be a feature, this has also created its fair share of headaches as well, so it is scheduled for deprecation/removal in future versions. (We might even provide a way to opt-out in 1.5.x as well.)
Note, that the behavior will be different, depending on whether or not your controller is recognized as a class (vs plain old constructor function).

**Comment by bcherny** [comment]
A backwards compatible way to make it work (at least in my case) would be getting rid of the 1st binding fire (caused by pre-assigning) rather than the 2nd binding fire -- is that what you mean?

So in 1.5.5 it was:

`call setter - call constructor - call setter`

In 1.5.6 it's:

`call setter - call constructor`

And what I'm proposing is:

`call constructor - cal setter`

**Comment by petebacondarwin** [comment]
`call constructor - call setter` is what we are aiming for in 1.6 but this would certainly break even more apps than the current change in 1.5.6

**Comment by bcherny** [comment]
Good to hear - at least for me, that would be an improvement!

**Comment by gkalpak** [comment]
Note that this is the behavior you might get today if your controller is a class (a real class).
I think it would be nice to introduce the new behavior as an opt-in in 1.5.x, so people that are eager for this get a chance to try it out early and we gather some feedback before 1.6 is out.
Something like:

```js
$compileProvider.enableBindingsPreAssignment(false);
```

The feature would be enabled by default on 1.5.x (so backwards compatible), but can be turned off.
Then on 1.6.x we will have it disabled by default (optionally allowing developers to turn it on).

**Comment by petebacondarwin** [comment]
@gkalpak I agree. But I think it should be simply:

```
$compileProvider.preAssignBindings(false);
```

**Comment by RobbertWolfs** [comment]
Is there any progress on this?
Because we just upgraded from 1.5.5 to 1.5.8 and we also have binding issues..

We have a component that requires a boolean value but it is always set to the default value.. not the one we use in the binding..

Some code: 

**in our test:**
`
   it('it has a required binding', () => {
               $scope.required = true';
               element = createDirective('<image-upload required="required"></image-upload>', $scope);
               controller = element.controller('imageUpload'); 
               expect(controller.required).to.eql(true);
});
`

**in our component**
`
   class ImageUploadController {
       // @ngInject
       constructor() {
           // DEFAULT BINDING
           this.required = false;
       }
   }
 
   export default {
       template: `my template`,
       controller: ImageUploadController,
       bindings: {
           required: '<?',
       },
   };
`

**Comment by gkalpak** [comment]
@RobbertWolfs, in case you haven't noticed, the related PR has been merged and the `preAssignBindingsEnabled` configuration switch will be available in an upcoming 1.5.x release :tada:
