### PR TITLE
fix(ngMock): handle cases where injector is created before tests

### LINKED ISSUE #10967: Angular fails to instantiate module ngLocale in tests after upgrade to 1.3.12
In our CI the tests failed, I tried to reproduce locally and could not until I removed our bower libs and reinstalled. (we were asking for ~1.3).
I played with bower.json angular versions and found that 1.3.11 works and 1.3.12 fails.

the code that breaks our app is found in commit 6ec5946094ee92b820bbacc886fa2367715e60b4

line 2138 in angular-mocks.js

     Error: [$injector:modulerr] Failed to instantiate module ng due to:
      Error: [$injector:modulerr] Failed to instantiate module ngLocale due to:
      TypeError: 'undefined' is not an object (evaluating 'annotatedFunctions.push')
      at /Volumes/OSxData/websites/startapp/portal/public/lib/angular-mocks/angular-mocks.js:2145
      at invoke (/Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4163)
      at instantiate (/Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4193)
      at provider (/Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4028)
      at /Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4020
      at runInvokeQueue (/Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4091)
      at /Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4099
      at forEach (/Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:323)
      at loadModules (/Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4123)
      at /Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4098
      at forEach (/Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:323)
      at loadModules (/Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4123)
      at createInjector (/Volumes/OSxData/websites/startapp/portal/public/lib/angular/angular.js:4007)
      at /Volumes/OSxData/websites/startapp/portal/public/lib/sinon-ng/sinon-ng.js:4
      at /Volumes/OSxData/websites/startapp/portal/public/lib/sinon-ng/sinon-ng.js:30

this occurs in angular-mocks therefore relevant only in testing environment

**Reproducable**: always
**Browsers** : Chrome 40, Phantom JS
**Operating system**: OSX 10.10, Ubuntu 14, Fedora 20

### PR DESCRIPTION
**Pull request by shahata**
This caused an exception for people who created an injector before the tests actually began to run. Since the array was initialized only in beforeEach, anyone accessing it before that would throw. This is solved easily but initializing the array immediately.

Closes #10967

### CODE REVIEW

File: test/ngMock/angular-mocksSpec.js [hunk 1]
```diff
@@ -776,6 +776,9 @@ describe('ngMock', function() {
 
           }
 
+          //this is only to make sure that we can create an injector outside of tests
+          angular.injector(['ng']);
```
Comment (lgalfaso) [inline test/ngMock/angular-mocksSpec.js]: please add this within a top level `define` with a test inside.

**Comment by lgalfaso** [comment]
other than that, let's wait for a green from Travis (or something that looks like green) and land this

**Comment by lgalfaso** [comment]
LGTM
